services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        command: [ "nginx", "-g", "daemon off;" ]

    db:
        image: mariadb:10.11
        container_name: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"   # AMQP protocol port
            - "15672:15672" # Management UI port
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    mariadb_data:
    rabbitmq_data:
